### PR TITLE
Switch freenode to libera chat

### PR DESCRIPTION
**Pull request by philipzae**

### CODE REVIEW

**Comment by philipzae** [comment]
@bluesabre maybe we should go with irc.ubuntu.com. what do you think.

**Comment by philipzae** [comment]
We should likely backport to 21.04 as well.

**Comment by philipzae** [comment]
Regarding irc.ubuntu.com, these were two messages from the ubuntu testers group/irc.

> <tomreyn> irc.ubuntu.com will only work for non-tls ("plain") connections
> @teward001: correct, that's something to keep in mind, irc.ubuntu.com won't work for TLS connections.

**Comment by bluesabre** [comment]
> Regarding irc.ubuntu.com, these were two messages from the ubuntu testers group/irc.
> 
> > irc.ubuntu.com will only work for non-tls ("plain") connections
> > @teward001: correct, that's something to keep in mind, irc.ubuntu.com won't work for TLS connections.

And that's an excellent reason to not use irc.ubuntu.com :)

**Comment by bluesabre** [comment]
> We should likely backport to 21.04 as well.

Since this is installed to /etc/skel, it's only copied to the user directory for newly created user accounts. To backport it to 21.04 would only affect user accounts created post-installation, so it wouldn't be very helpful.

**Comment by philipzae** [comment]
> Since this is installed to /etc/skel, it's only copied to the user directory for newly created user accounts. To backport it to 21.04 would only affect user accounts created after installing and updating post-installation, so it wouldn't be very helpful.

If someone installs 21.04 from the iso and enables updates during installation, would the new backported package not fix the issue for them?

**Comment by bluesabre** [comment]
You may need to check with somebody else, but I believe the "updates during installation" feature just downloads them. Once you start the installed session, you are then prompted to install the updates.

**Pull request merged**
