### PR TITLE
Add Clipman to panel

### PR DESCRIPTION
**Pull request by philipzae**
patch for #14

### CODE REVIEW

**Comment by bluesabre** [comment]
I feel uncomfortable about adding Clipman to the panel by default since it automatically records the clipboard. Please bring this to a team vote first.

**Comment by philipzae** [comment]
Vote requested on ML. https://lists.ubuntu.com/archives/xubuntu-devel/2021-May/012090.html

**Comment by DarkTrick** [comment]
Vote against.

Reasons here:
1. It's beyond the solution of the problem "fix X11's clipboard clearing bug"
2. Having a clipboard history might be surprising for users and might affect security (people copying passwords around)
3. In my personal experience, clipman worsened the situation. I had quite a couple of bug encounters.

**Comment by knomepasi** [comment]
A "team vote" means people in the Xubuntu team (https://launchpad.net/~xubuntu-team/+members#active) should vote about this, not the community. I've also sent a message to the mailing list to avoid further confusion.

**Comment by knomepasi** [comment]
My vote is -1.

We do not want to include any packages recording users' input-related activity, even if it was recorded on their local machines only. Those who actively want this feature can install it easily from the repository.

**Comment by bluesabre** [comment]
My vote is likewise -1. Automatically recording the clipboard without any indication or permission from the user is a no-go from me.

**Comment by philipzae** [comment]
What about adding clipman to the panel and have it not record the clipboard history automatically by disabling the 'Remember history' checkbox in preferences?

image

**Comment by bluesabre** [comment]
@philipzae From what I can tell, that setting doesn't do anything. Clipboard contents are still captured. Even if it did, it really doesn't to add the clipboard manager to the panel and then have it do nothing. I've sent a follow-up to the mailing list for the rest of the team to vote.

**Comment by bluesabre** [comment]
+1 Yousuf
-1 Pasi
-1 Myself
+1 Krytarik
-1 Simon (#xubuntu-devel, 11/11/21)
(not heard from @unit193 or @pleia2 yet)

**Comment by bluesabre** [comment]
No further votes. Closing this one out.

**Pull request closed without merging**
