### PR TITLE
fix super turning into caps when user swaps caps and esc

### PR DESCRIPTION
**Pull request by ourtable**
A PR form of the patches in [this](https://bugs.launchpad.net/ubuntu/+source/xubuntu-default-settings/+bug/1961506) bug report. Changes the xcape binding for super and it's matching shortcut for whiskermenu from `LCtrl+Esc` to `LAlt+Pause` to prevent super from turning into capslock when running commands like `setxkbmap -option caps:swapescape`

### CODE REVIEW

**Comment by bluesabre** [comment]
Primary + Escape is an upstream Xfce keyboard shortcut. I'd prefer if an additional shortcut was added instead and used.

**Comment by ourtable** [comment]
> Primary + Escape is an upstream Xfce keyboard shortcut. I'd prefer if an additional shortcut was added instead and used.

What exactly do you mean by this? I'm not sure what you're asking me to do.

**Comment by ourtable** [comment]
> Primary + Escape is an upstream Xfce keyboard shortcut. I'd prefer if an additional shortcut was added instead and used.

@bluesabre What exactly do you mean by this? I'm not sure what you're asking me to do.

**Comment by ourtable** [comment]
changed the bind from <kbd>LShift+LCtrl+LAlt+LSuper</kbd> to <kbd>LAlt+Pause</kbd>

**Comment by bluesabre** [comment]
Thanks!

**Pull request merged**
